# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GI6xvGMxiURa_RkeE7ASRlAN5lqij0Hp
"""

import streamlit as st
import pandas as pd

st.title('고객 이탈 예측')
st.subheader('데이터셋을 업로드 하세요')
uploaded_file = st.file_uploader("csv file upload", type = ["csv"])
if uploaded_file is not None:
  data = pd.read_csv(uploaded_file)
  st.write(data.head())